version: '3'
services:
  service1:
    image: openjdk:11-jdk-slim-buster
    volumes:
      - ./generated/heartbeat-middleware.jar:/app/heartbeat-middleware.jar
    command: ["java", "-jar", "/app/heartbeat-middleware.jar", "FOLLOWER"]
    ports:
      - "8080:80"
  service2:
    image: openjdk:11-jdk-slim-buster
    volumes:
      - ./generated/heartbeat-middleware.jar:/app/heartbeat-middleware.jar
    command: ["java", "-jar", "/app/heartbeat-middleware.jar", "FOLLOWER"]
    ports:
      - "8081:80"
#  service3:
#    image: openjdk:11-jdk-slim-buster
#    volumes:
#      - ./generated/heartbeat-middleware.jar:/app/heartbeat-middleware.jar
#    command: ["java", "-jar", "/app/heartbeat-middleware.jar", "FOLLOWER"]
#    ports:
#      - "8082:80"
#  service4:
#    image: openjdk:11-jdk-slim-buster
#    volumes:
#      - ./generated/heartbeat-middleware.jar:/app/heartbeat-middleware.jar
#    command: ["java", "-jar", "/app/heartbeat-middleware.jar", "FOLLOWER"]
#    ports:
#      - "8083:80"