version: '3'
services:
  coordinator:
    image: openjdk:11-jdk-slim-buster
    volumes:
      - ./generated:/app
      - ./generated/heartbeat-middleware.jar:/app/heartbeat-middleware.jar
    working_dir: /app
    command: ["java", "-jar", "/app/heartbeat-middleware.jar", "COORDINATOR"]
    user: root
    ports:
      - "8080:80"
    networks:
      ds:
        ipv4_address: 172.18.0.2
  follower1:
    image: openjdk:11-jdk-slim-buster
    volumes:
      - ./generated:/app
      - ./generated/heartbeat-middleware.jar:/app/heartbeat-middleware.jar
    working_dir: /app
    command: ["java", "-jar", "/app/heartbeat-middleware.jar", "FOLLOWER"]
    user: root
    ports:
      - "8081:80"
    networks:
      ds:
        ipv4_address: 172.18.0.3
  follower2:
    image: openjdk:11-jdk-slim-buster
    volumes:
      - ./generated:/app
      - ./generated/heartbeat-middleware.jar:/app/heartbeat-middleware.jar
    working_dir: /app
    command: ["java", "-jar", "/app/heartbeat-middleware.jar", "FOLLOWER_BEAT_SENDER"]
    user: root
    ports:
      - "8082:80"
    networks:
      ds:
        ipv4_address: 172.18.0.4
  follower3:
    image: openjdk:11-jdk-slim-buster
    volumes:
      - ./generated:/app
      - ./generated/heartbeat-middleware.jar:/app/heartbeat-middleware.jar
    working_dir: /app
    command: ["java", "-jar", "/app/heartbeat-middleware.jar", "FOLLOWER_BEAT_SENDER"]
    user: root
    ports:
      - "8083:80"
    networks:
      ds:
        ipv4_address: 172.18.0.5
  follower4:
    image: openjdk:11-jdk-slim-buster
    volumes:
      - ./generated:/app
      - ./generated/heartbeat-middleware.jar:/app/heartbeat-middleware.jar
    working_dir: /app
    command: ["java", "-jar", "/app/heartbeat-middleware.jar", "FOLLOWER"]
    user: root
    ports:
      - "8084:80"
    networks:
      ds:
        ipv4_address: 172.18.0.6
networks:
  ds:
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/16
          gateway: 172.18.0.1